name: Cypress tests
on: 
 push:
     branches: [ gatsby-ver ]
 pull_request:
     branches: [ gatsby-ver ]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: lorem-travels-gatsby
          build: npm run build
          start: npm run serve:ci
          wait-on: 'http://localhost:8000'
          env:
            CI=true
            PROD_URL='http://localhost:8000'
          config: 'baseUrl=http://localhost:8000'
